import type { TextElement } from "@/types/timeline";

export type TextTemplateCategory =
	| "title"
	| "end-screen"
	| "callout"
	| "social";

export const TEXT_TEMPLATE_CATEGORIES = [
	"title",
	"end-screen",
	"callout",
	"social",
] as const;

export const TEXT_TEMPLATE_CATEGORY_LABELS: Record<
	TextTemplateCategory,
	string
> = {
	title: "Title Cards",
	"end-screen": "End Screens",
	callout: "Callouts",
	social: "Social Handles",
};

export interface TextTemplate
	extends Omit<
		TextElement,
		"id" | "startTime" | "trimStart" | "trimEnd" | "duration"
	> {
	templateId: string;
	category: TextTemplateCategory;
	/** Preview label shown in the gallery card */
	previewText: string;
}

export const TEXT_TEMPLATES: TextTemplate[] = [
	// ---- Title Cards ----
	{
		templateId: "title-bold",
		category: "title",
		previewText: "BOLD TITLE",
		type: "text",
		name: "Title",
		content: "Your Title Here",
		fontSize: 10,
		fontFamily: "Impact",
		color: "#ffffff",
		backgroundColor: "transparent",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		stroke: { color: "#000000", width: 4 },
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
	{
		templateId: "title-elegant",
		category: "title",
		previewText: "Elegant Title",
		type: "text",
		name: "Title",
		content: "Your Title Here",
		fontSize: 10,
		fontFamily: "Georgia",
		color: "#ffffff",
		backgroundColor: "transparent",
		textAlign: "center",
		fontWeight: "normal",
		fontStyle: "italic",
		textDecoration: "none",
		opacity: 1,
		shadow: { color: "#000000", offsetX: 0, offsetY: 4, blur: 12 },
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
	{
		templateId: "title-neon",
		category: "title",
		previewText: "NEON",
		type: "text",
		name: "Title",
		content: "Your Title Here",
		fontSize: 10,
		fontFamily: "Arial",
		color: "#00ffff",
		backgroundColor: "transparent",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		shadow: { color: "#00ffff", offsetX: 0, offsetY: 0, blur: 16 },
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
	// ---- End Screens ----
	{
		templateId: "end-subscribe",
		category: "end-screen",
		previewText: "SUBSCRIBE",
		type: "text",
		name: "End Screen",
		content: "Subscribe for more!",
		fontSize: 10,
		fontFamily: "Arial",
		color: "#ffffff",
		backgroundColor: "#cc0000",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		backgroundBorderRadius: 8,
		backgroundPaddingX: 24,
		backgroundPaddingY: 12,
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
	{
		templateId: "end-thanks",
		category: "end-screen",
		previewText: "Thanks for watching",
		type: "text",
		name: "End Screen",
		content: "Thanks for watching!",
		fontSize: 10,
		fontFamily: "Georgia",
		color: "#ffffff",
		backgroundColor: "transparent",
		textAlign: "center",
		fontWeight: "normal",
		fontStyle: "italic",
		textDecoration: "none",
		opacity: 1,
		shadow: { color: "#000000", offsetX: 0, offsetY: 2, blur: 8 },
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
	// ---- Callouts ----
	{
		templateId: "callout-arrow",
		category: "callout",
		previewText: "→ Look here!",
		type: "text",
		name: "Callout",
		content: "→ Look at this!",
		fontSize: 10,
		fontFamily: "Arial",
		color: "#ffff00",
		backgroundColor: "rgba(0, 0, 0, 0.7)",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		backgroundBorderRadius: 6,
		backgroundPaddingX: 14,
		backgroundPaddingY: 6,
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
	{
		templateId: "callout-circle",
		category: "callout",
		previewText: "🔴 NEW",
		type: "text",
		name: "Callout",
		content: "NEW",
		fontSize: 10,
		fontFamily: "Arial",
		color: "#ffffff",
		backgroundColor: "#ff6600",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		backgroundBorderRadius: 100,
		backgroundPaddingX: 20,
		backgroundPaddingY: 14,
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
	// ---- Social Handles ----
	{
		templateId: "social-handle",
		category: "social",
		previewText: "@yourhandle",
		type: "text",
		name: "Social",
		content: "@yourhandle",
		fontSize: 10,
		fontFamily: "Inter",
		color: "#ffffff",
		backgroundColor: "rgba(0, 0, 0, 0.6)",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		backgroundBorderRadius: 4,
		backgroundPaddingX: 12,
		backgroundPaddingY: 6,
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
	{
		templateId: "social-follow",
		category: "social",
		previewText: "Follow ↓",
		type: "text",
		name: "Social",
		content: "Follow for more ↓",
		fontSize: 10,
		fontFamily: "Arial",
		color: "#ffffff",
		backgroundColor: "transparent",
		textAlign: "center",
		fontWeight: "normal",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		stroke: { color: "#000000", width: 2 },
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
];
